s3:
  bucket:
    name: inkeun-bucket
    base-path: study/image

spring:
  datasource:
    url: jdbc:postgresql://db-rds-study.c4vf81iso7gb.ap-northeast-2.rds.amazonaws.com/db_rds_study
  jpa:
    show-sql: true
#  session:
#    store-type: redis
  redis:
    host: localhost
  rabbitmq:
    host: ec2-54-180-24-89.ap-northeast-2.compute.amazonaws.com
    port: 5672
    virtual-host: develop

server:
  port: 5000
